### ISSUE TITLE
feature: add check for a newer version of this script from within script

### ISSUE THREAD

**Issue by klodeckl** [LucasLarson/update#15]
Hello, I just found your script, I like it! How about a self update for the update script?

**Comment by LucasLarson** [comment]
> I like it!

Thank you!

> How about a self update

What do you have in mind?

**Comment by klodeckl** [comment]
Check the version of the file in github and download the new version if available? (But I think my knowledge is too poor to help to develop this.)

**Comment by LucasLarson** [comment]
Oh that’s a great idea – it didn’t occur to me since I built it just for me.

**Comment by LucasLarson** [comment]
> Check the version of the file in github and download the new version if available

I removed a manually added timestamp in [`c173aaec9cb`](https://github.com/LucasLarson/update/commit/c173aaec9cb#diff-2937013f2181810606b2a799b05bda2849f3e369a20982a4138f0e0a55984ce4L126). Restoring it and comparing it to the output of
```shell
command date -- '+%Y-%m-%d'
```

is probably the lowest-tech way to add this functionality

**Comment by klodeckl** [comment]
I don’t really understand, you want to compare the current date of execution with a timestamp?
Why not add a version number in the script and compare it with a version file in the github master branch?
As I remember rpi update (https://github.com/raspberrypi/rpi-update) has a self update included, maybe this could be used as inspiration.
